server:
  port: 8025
spring:
  profiles:
    active: test
  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:vess-web-dev-test
---
spring:
  config:
    activate:
      on-profile: prod-postgres
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/vess-web-dev-prod
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop